config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

 resources :products
 resources :stores, only: [:index, :show, :new, :create]
 
 root to: "products#index"
 
 get 'login', to: 'sessions#new'
 post 'login', to: 'sessions#create'
 delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :store
  mount_uploader :image, ImageUploader
  
  validates :image, presence: false
  validates :title, presence: true, length: {maximum:100}
  validates :capture, presence: false, length: {maximum:500}
  validates :price, presence: true, format: { with: /\A[0-9]+\z/ }
  
  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_secure_password
  before_save { self.email.downcase! }
  has_many :products
  
  validates :name, presence: true, length: {maximum:100}
  validates :email, presence:true, length: {maximum:255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },uniqueness: { case_sensitive: false }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private

  def require_store_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_store_logged_in, only: [:new, :create, :edit, :destroy]
  before_action :correct_store, only: [:destroy]
  
  def index
    @products = Product.search(params[:search]).page(params[:page])
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = current_store.products.build(product_params)

    if @product.save
      flash[:success] = '商品を登録しました。'
      redirect_to products_url
    else
      flash.now[:danger] = '商品の登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      flash[:success] = '正常に更新されました'
      redirect_to products_url
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end
  
  def destroy
    @product.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private

  def product_params
    params.require(:product).permit(:image, :title, :capture, :price)
  end
  
  def correct_store
    @product = current_store.products.find_by(id: params[:id])
    unless @product
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @store
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:store_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @store = Store.find_by(email: email)
    if @store && @store.authenticate(password)
      session[:store_id] = @store.id
      return true
    else
      return false
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all.page(params[:page])
  end

  def show
    @store = Store.find(params[:id])
    @products = @store.products.order("created_at DESC").page(params[:page])
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new(store_params)

    if @store.save
      flash[:success] = '店舗を登録しました。'
      redirect_to @store
    else
      flash.now[:danger] = '店舗の登録に失敗しました。'
      render :new
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_store
    @current_store ||= Store.find_by(id: session[:store_id])
  end

  def logged_in?
    !!current_store
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_error_massages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_massages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-static-top" style="background-color:#e0e0e0;">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Shopping</a>
      </div>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to '商品の登録', new_product_path %></li>
            <li><%= link_to '商品一覧', products_path %></li>
            <li><%= link_to '店舗一覧', stores_path %></li>
            <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to '商品一覧', products_path %></li>
            <li><%= link_to '店舗一覧', stores_path %></li>
            <li><%= link_to '店舗新規登録', new_store_path %></li>
            <li><%= link_to '店舗アカウントにログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
      
    <div class="text-center"> <!-- 検索フォーム -->
      <div class="text-muted"><p>商品を検索</p></div>
        <%= form_tag(products_path, :method => "get") do %>
          <%= text_field_tag :search %>
          <%= submit_tag "検索", :title => nil %>
        <% end %>  
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Shopping</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_products.html.erb
<% if products.any? %>
  <ul class="media-list">
    <% products.each do |product| %>
      <li class="media">
        <div class="media-left">
          <% if product.image? %>
　　        <%= image_tag product.image, :size => "100x100" %>
　        <% else %>
　　        <%= image_tag "noimage.png", :size => "100x100" %>
　        <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= link_to product_path(product) do %>
              <h4><%= product.title %></h4>
            <% end %>
          </div>
          <div>
            <h3><%= product.price %>円</h3>
          </div>
          <div>
            <%= product.capture %>
          </div>
          
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate products %>
<% else %>
  <p>商品がありません</p>
<% end %>

app/views/products/edit.html.erb
<div class="text-center">
  <h1>商品情報の編集</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@product) do |f| %>
    
      <div>
        <%= f.label :image, "画像" %>
　　    <%= f.file_field :image %>
      </div>

      <div class="form-group">
        <%= f.label :title, '商品タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :capture, '商品の説明' %>
        <%= f.text_area :capture, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price, '価格' %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<%= render "products", products: @products %>

app/views/products/new.html.erb
<div class="text-center">
  <h1>商品の登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@product) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div>
        <%= f.label :image, "画像" %>
　　    <%= f.file_field :image %>
      </div>

      <div class="form-group">
        <%= f.label :title, '商品タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :capture, '商品の説明' %>
        <%= f.text_area :capture, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :price, '価格' %>
        <%= f.text_field :price, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-xs-10"> 
  
    <div class="text-center">
　    <h3><%= @product.title %></h3>
　    <p>この商品を売っているお店：<%= link_to @product.store.name, store_path(@product.store) %></p>
　  </div>
　  
    <div class="text-center" id="show_image">
      <% if @product.image? %>
　　    <%= image_tag @product.image, :size => "500x500" %>
　    <% else %>
　　    <%= image_tag "noimage.png", :size => "500x500" %>
　    <% end %>
　  </div>
　  
　  <div class="text-center">
      <h2><%= @product.price %>円</h2>
    </div>
    
    <div class="text-center"> 
      <%= @product.capture %>
    </div>
    
    <% if current_store == @product.store %>
    <div class="text-right">
      <%= link_to "編集", edit_product_path(@product) %>
      <%= link_to "削除", @product, method: :delete, data: { confirm: "本当に削除してよろしいですか？" } %> 
    <% end %>  
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<% if @stores.any? %>
  <ul class="media-list">
    <% @stores.each do |store| %>
      <li>
        <div>
          <%= link_to store_path(store) do %>
            <h4>・<%= store.name %></h4>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @stores %>
<% end %>

app/views/stores/new.html.erb
<div class="text-center">
  <h1>新規店舗登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@store) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %> <!-- error message -->
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/stores/show.html.erb
<div class="row">
  <div class="col-xs-10"> 
  
    <div class="text-center">
　    <h3><%= @store.name %></h3>
　  </div>
　  
　  <% if @products.any? %>
　    <p>この店舗の商品</p>
　    <%= render "products/products", products: @products %>
　  <% else %>
　    <p>この店舗の商品はまだありません</p>
　  <% end %>
  </div>
</div>